---

- name: Generate VM names if VMS > 0, else use a single VM name
  tags: deploy
  ansible.builtin.set_fact:
    vm_names: >
      {{
        [vm_name] if (vm_count | default(0) | int) == 0 else
        query('sequence', "start=1 end={{ vm_count | int }} format={{ vm_name }}-%d")
      }}

- name: Deploy VMs
  tags: deploy
  ansible.builtin.include_tasks: deploy_vm.yml
  loop: "{{ vm_names }}"
  loop_control:
    loop_var: current_vm_name
