---

- name: Check that the cloud-init file exists
  tags: dowload_img
  stat:
    path: "{{ ext_storage }}/{{ img_name }}"
  register: stat_result

- name: Dowload cloud-init image
  tags: dowload_img
  ansible.builtin.get_url:
    url: "{{ img_url }}"
    dest: "{{ ext_storage }}"
    mode: '0644'
    force: true
    timeout: 500
  when: not stat_result.stat.exists
