---

- name: Update apt cache
  tags: configure
  ansible.builtin.apt:
    update_cache: true

- name: Install the main apps
  tags: configure
  ansible.builtin.apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present
  loop:
    - python3-pip
    - python3-dev
    - python3-virtualenv
    - python3-proxmoxer
    - python3-requests
    - build-essential
    - libguestfs-tools

- name: Clean Up the Cache
  tags: configure
  ansible.builtin.apt:
    autoclean: true
    autoremove: true