---

- name: Install the main apps
  tags: pve_config
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - python3-dev
      - python3-virtualenv
      - python3-proxmoxer
      - python3-requests
      - build-essential
      - libguestfs-tools
    update_cache: true
    install_recommends: yes
    state: present

# - name: Installing the app pip on PVE nodes
#   tags: pve_config
#   ansible.builtin.apt:
#     name: pip
#     update_cache: true
#     install_recommends: false
#     state: present

# - name: Installing the app Virtualenv on PVE nodes
#   tags: pve_config
#   ansible.builtin.pip:
#     name: virtualenv
#     state: present

# - name: Installing the app Proxmoxer on PVE nodes
#   tags: pve_config
#   ansible.builtin.pip:
#     name: proxmoxer
#     version: 2.0.1
#     state: present

# - name: Installing the app Requests on PVE nodes
#   tags: pve_config
#   ansible.builtin.pip:
#     name: requests
#     state: present