---

- name: Initialization of a new VM on the ProxmoxVE servers
  hosts: proxmox
  
  roles:
    - { role: roles/configure, tags: ['configure'] }
    - { role: roles/dowload, tags: ['dowload'] }
    - { role: roles/customize, tags: ['dowload'] }
    - { role: roles/deploy, tags: ['deploy'] }